# Assignment 0 - Foundations of Machine Learning
#### Ahmik Virani
#### ES22BTECH11001

In [2]:
# (a) Import the numpy package under the name np. Print the numpy version and the configuration.

import numpy as np
print(np. __version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4335021056
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    commands: cc
    linker: ld64
    linker args: -fno-strict-aliasing, -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    name: clang
    version: 14.0.0
  c++:
    args: -DBLAS_SYMBOL_SUFFIX=64_, -DHAVE_BLAS_ILP64
    commands: c++
    linker: ld64
   

In [3]:
# (b) Create a null vector of size 10, and output the vector to the terminal.

null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# (c) Create a null vector of size 10 but the fifth value which is 1. Output the vector to the terminal.

null_vector = np.zeros(10)
null_vector[4] = 1      #0 based indexing
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# (d) Reverse a vector (first element becomes last).

vector = np.array([1, 2, 3, 4, 5])
reverse_vector = np.flip(vector)
print(reverse_vector)

[5 4 3 2 1]


In [6]:
# (e) Create an n × n array with checkerboard pattern of zeros and ones.

n = 5   #specify the value of 'n'

checkboard = np.zeros((n, n))
checkboard[1::2, ::2] = 1   #1's on odd rows and even columns
checkboard[::2, 1::2] = 1   #1's on even rows and odd columns

print(checkboard)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [7]:
# (f) Given an n × n array, sort the rows of array according to mth column of array.

n = 4   #specify the value of 'n'

array = np.array([[4, 2, 3, 1],         #Specify an n*n array
                  [1, 3, 4, 2],
                  [2, 1, 3, 4],
                  [3, 4, 2, 1]])
    
m = 2                                   #Specify a value of m

sorted_array = array[array[:,m].argsort()]
print(sorted_array)

[[3 4 2 1]
 [4 2 3 1]
 [2 1 3 4]
 [1 3 4 2]]


In [8]:
# (g) Create an n × n array with (i + j)th-entry equal to i + j.

n = 3                   #Specify n

rows = np.arange(n).reshape(n, 1)       #specify row matrix
columns = np.arange(n)                  #specify column matrix

required_arr = rows + columns           #broadcasting to create the desired array
print(required_arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [9]:
# (h) Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element (of the entire structure)?

shape = (6, 7, 8)
index = 100
result = np.unravel_index(index, shape)     #convert the flat index into coordinates in the multi-dimensional array
print(result)


(1, 5, 4)


In [10]:
# (i) Multiply a 5 × 3 matrix by a 3 × 2 matrix (real matrix product).

A = np.full((5, 3), 3)      #Call the first matrix A
B = np.full((3, 2), 2)      #Call the second matrix B

res = np.matmul(A, B)
print(res)

[[18 18]
 [18 18]
 [18 18]
 [18 18]
 [18 18]]


In [11]:
# (j) Create random vector of size 10 and replace the maximum value by 0.

vector = np.random.rand(10)
max_index = np.argmax(vector)       # Find the index of the maximum value
vector[max_index] = 0

print(vector)

[0.85337976 0.28495096 0.43508616 0.         0.14293896 0.83635915
 0.75550405 0.27037299 0.57947379 0.29049524]


In [12]:
# (k) How to find the closest value (to a given scalar) in an array?

scalar = 9

array = np.array([1, 3, 7, 15, 20])
difference_array = np.abs(array - scalar)       #Create an array that stores the difference between scalar and array values
closest_index = np.argmin(difference_array)     #Find the index of the minimum difference

print(array[closest_index])

7


In [13]:
# (l) Subtract the mean of each row from each corresponding row of a matrix.

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_mean = np.mean(matrix, axis = 1)
matrix = matrix - row_mean[:, np.newaxis]
print(matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [14]:
# (m) Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices - you should consider it only once)?

given_vector = np.array([10, 4, 6 , 1, 6, 8])
index_vector = np.array([1, 2, 2, 4])

unique_indices = np.unique(index_vector)  #Ensure the index_vector is unique

given_vector[unique_indices] += 1               #For all index_vector values, add 1
print(given_vector)

[10  5  7  1  7  8]


In [15]:
# (n) How to find the most frequent value in an array?

array = np.array([1, 2, 3, 2, 2, 1, 4, 5])
values, counts = np.unique(array, return_counts=True)

max_index = np.argmax(counts)
most_frequent_value = values[max_index]

print(most_frequent_value)

2


In [16]:
# (o) Extract all the contiguous 3 × 3 blocks from a random 10 × 10 matrix.

from numpy.lib.stride_tricks import sliding_window_view

matrix = np.random.rand(10, 10)                 # Generate a random 10x10 matrix
blocks = sliding_window_view(matrix, (3, 3))    # Use sliding_window_view to extract all contiguous 3x3 blocks

print(blocks)

[[[[0.48448393 0.02148045 0.81007862]
   [0.9857971  0.82944367 0.66858232]
   [0.84948799 0.21755013 0.39855683]]

  [[0.02148045 0.81007862 0.34668989]
   [0.82944367 0.66858232 0.78089653]
   [0.21755013 0.39855683 0.88389817]]

  [[0.81007862 0.34668989 0.27642839]
   [0.66858232 0.78089653 0.67572013]
   [0.39855683 0.88389817 0.50865056]]

  [[0.34668989 0.27642839 0.47256852]
   [0.78089653 0.67572013 0.48866416]
   [0.88389817 0.50865056 0.91230676]]

  [[0.27642839 0.47256852 0.72037324]
   [0.67572013 0.48866416 0.3914267 ]
   [0.50865056 0.91230676 0.97729872]]

  [[0.47256852 0.72037324 0.55552326]
   [0.48866416 0.3914267  0.37638099]
   [0.91230676 0.97729872 0.60930747]]

  [[0.72037324 0.55552326 0.16876255]
   [0.3914267  0.37638099 0.04389439]
   [0.97729872 0.60930747 0.35183959]]

  [[0.55552326 0.16876255 0.85613418]
   [0.37638099 0.04389439 0.23753615]
   [0.60930747 0.35183959 0.97536579]]]


 [[[0.9857971  0.82944367 0.66858232]
   [0.84948799 0.21755013 0.3985

In [17]:
# (p) Compute the rank, trace and determinant of a matrix.

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

# Compute the trace of the matrix
trace = np.trace(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"Rank: {rank}")
print(f"Trace: {trace}")
print(f"Determinant: {determinant}")

Rank: 2
Trace: 15
Determinant: -9.51619735392994e-16
